// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkfL6cQcrX2cXiPso_P5pt0CKLBY9I7vI',
    appId: '1:613253088591:web:b077c539fc46346a44f13a',
    messagingSenderId: '613253088591',
    projectId: 'meditation-cf5b9',
    authDomain: 'meditation-cf5b9.firebaseapp.com',
    storageBucket: 'meditation-cf5b9.appspot.com',
    measurementId: 'G-PVEJT3BCPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtHUZEtay-tVL8dlZWXXHu10-0wKT-Q-M',
    appId: '1:613253088591:android:27e06144841e102044f13a',
    messagingSenderId: '613253088591',
    projectId: 'meditation-cf5b9',
    storageBucket: 'meditation-cf5b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDSBfdKbFaPJRn7F-nF7owDZWaDIVd2J4',
    appId: '1:613253088591:ios:c96906b08488551e44f13a',
    messagingSenderId: '613253088591',
    projectId: 'meditation-cf5b9',
    storageBucket: 'meditation-cf5b9.appspot.com',
    iosBundleId: 'com.example.meditation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDSBfdKbFaPJRn7F-nF7owDZWaDIVd2J4',
    appId: '1:613253088591:ios:4e09d06f0ca0d12b44f13a',
    messagingSenderId: '613253088591',
    projectId: 'meditation-cf5b9',
    storageBucket: 'meditation-cf5b9.appspot.com',
    iosBundleId: 'com.example.meditation.RunnerTests',
  );
}
